
services:
  db:
    image:  postgres:15.5
    container_name: postgres-db
    environment:
      POSTGRES_DB:  coffeeMap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

volumes:
  db-data:
